# Generated by Django 5.0.4 on 2024-05-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='day',
        ),
    ]
